reloader:
  watchGlobally: false
  autoReloadAll: true
  reloadOnCreate: true
  syncAfterRestart: true
  reloadStrategy: default
  ignoreJobs: true

image:
  repository: {{ .Repo}}
  tag: {{ .Tag }}
  pullPolicy: IfNotPresent

